spring:
  application:
    name: cleat-api


  datasource:
    url: jdbc:postgresql://localhost:5432/cleat_test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    defaults:
      enabled: true
    redis:
      enabled: false
    db:
      enabled: false


